name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every 24 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Snake Game from Contributions
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: kasimkazmi
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          # Use your personal token (GH_TOKEN) instead of default
          token: ${{ secrets.GH_TOKEN }}